#!/bin/sh
AUZIX_PACKAGE_ROOT=${AUZIX_PACKAGE_ROOT:-/Programs/OpensshServer/1-10.0p1-7+deb13u4}
AUZIX_SETTINGS=${AUZIX_SETTINGS:-/System/Settings}
AUZIX_STATE=${AUZIX_STATE:-/System/State}
AUZIX_CACHE=${AUZIX_CACHE:-/System/Cache}
AUZIX_LOGS=${AUZIX_LOGS:-/System/Logs}
AUZIX_RUN=${AUZIX_RUN:-/System/Run}
AUZIX_TMP=${AUZIX_TMP:-/Work/Temp}
AUZIX_ROOT_USER=${AUZIX_ROOT_USER:-/Users/root}
export AUZIX_PACKAGE_ROOT AUZIX_SETTINGS AUZIX_STATE AUZIX_CACHE AUZIX_LOGS
export AUZIX_RUN AUZIX_TMP AUZIX_ROOT_USER
auzix_ensure_system_account() {
	account=$1
	id "$account" >/dev/null 2>&1 && return 0
	if command -v adduser >/dev/null 2>&1; then
		adduser --system --quiet --group "$account" || true
	fi
	id "$account" >/dev/null 2>&1 && return 0
	groupadd --system "$account" 2>/dev/null || true
	useradd --system --gid "$account" --no-create-home --shell /usr/sbin/nologin "$account"
}
auzix_apply_statoverride() {
	user=$1
	group=$2
	mode=$3
	path=$4
	[ -n "$path" ] && [ ! -L "$path" ] && [ -e "$path" ] || return 0
	id "$group" >/dev/null 2>&1 || return 1
	chown "$user:$group" "$path"
	chmod "$mode" "$path"
}
auzix_upgrade_cmp() {
	previous=$1
	_operator=$2
	_than=$3
	[ -n "$previous" ] || return 1
	return 1
}
auzix_apply_sysctl() {
	pattern=$1
	command -v sysctl >/dev/null 2>&1 || return 0
	sysctl --quiet --pattern "$pattern" --system || true
}
auzix_needed_step() {
	kind=${1:-own}
	shift || true
	case "$kind" in
	list)
		find "${AUZIX_PACKAGE_ROOT}/RootFS" 2>/dev/null || true
		;;
	rename)
		[ -n "$1" ] && [ -n "$2" ] && [ -e "$1" ] && [ ! -e "$2" ] && mv -- "$1" "$2" || true
		;;
	own)
		return 0
		;;
	trigger|named)
		name=${1:-}
		if [ "$name" = update-initramfs ] && command -v update-initramfs >/dev/null 2>&1; then
			update-initramfs -u || true
		fi
		if [ "$name" = ldconfig ] && command -v ldconfig >/dev/null 2>&1; then
			ldconfig || true
		fi
		return 0
		;;
	*)
		return 0
		;;
	esac
}
auzix_maintainer_main() {
set -e

: # stripped donor debconf import

: # stripped donor debconf


action="$1"

umask 022


get_config_option() {
	option="$1"
	sshd_path=${AUZIX_PACKAGE_ROOT}/RootFS/usr/sbin/sshd

	[ -f ${AUZIX_SETTINGS}/ssh/sshd_config ] || return

	# begin-remove-after: released:forky
	if [ -e /System/Compatibility/sbin/sshd.session-split ]; then
		sshd_path=/System/Compatibility/sbin/sshd.session-split
	fi
	# end-remove-after
	"$sshd_path" -G | sed -n "s/^$option //Ip"
}


create_key() {
	msg="$1"
	shift
	hostkeys="$1"
	shift
	file="$1"
	shift

	if echo "$hostkeys" | grep -x "$file" >/dev/null && \
	   [ ! -f "$file" ] ; then
		printf %s "$msg"
		ssh-keygen -q -f "$file" -N '' "$@"
		echo
		if command -v restorecon >/dev/null 2>&1; then
			restorecon "$file" "$file.pub"
		fi
		ssh-keygen -l -f "$file.pub"
	fi
}


create_keys() {
	hostkeys="$(get_config_option HostKey)"

	create_key "Creating SSH2 RSA key; this may take some time ..." \
		"$hostkeys" ${AUZIX_SETTINGS}/ssh/ssh_host_rsa_key -t rsa
	create_key "Creating SSH2 ECDSA key; this may take some time ..." \
		"$hostkeys" ${AUZIX_SETTINGS}/ssh/ssh_host_ecdsa_key -t ecdsa
	create_key "Creating SSH2 ED25519 key; this may take some time ..." \
		"$hostkeys" ${AUZIX_SETTINGS}/ssh/ssh_host_ed25519_key -t ed25519
}


new_config=

cleanup() {
	if [ "$new_config" ]; then
		rm -f "$new_config"
	fi
}


create_sshdconfig() {
	# XXX cjwatson 2016-12-24: This debconf template is very confusingly
	# named; its description is "Disable SSH password authentication for
	# root?", so true -> prohibit-password (the upstream default),
	# false -> yes.
	: # stripped donor debconf

	permit_root_login="$RET"
	: # stripped donor debconf

	password_authentication="$RET"

	trap cleanup EXIT
	new_config="$(mktemp)"
	cp -aZ ${AUZIX_PACKAGE_ROOT}/RootFS/usr/share/openssh/sshd_config "$new_config"
	if [ "$permit_root_login" != true ]; then
		sed -i 's/^#*PermitRootLogin .*/PermitRootLogin yes/' \
			"$new_config"
	fi
	if [ "$password_authentication" != true ]; then
		sed -i 's/^#PasswordAuthentication .*/PasswordAuthentication no/' \
			"$new_config"
	fi
	mkdir -pZ ${AUZIX_SETTINGS}/ssh
	ucf --three-way --debconf-ok \
		--sum-file ${AUZIX_PACKAGE_ROOT}/RootFS/usr/share/openssh/sshd_config.md5sum \
		"$new_config" ${AUZIX_SETTINGS}/ssh/sshd_config
	ucfr openssh-server ${AUZIX_SETTINGS}/ssh/sshd_config
}

if [ "$action" = configure ]; then
	create_sshdconfig
	create_keys
	if auzix_upgrade_cmp "$2" lt-nl 1:7.9p1-5 && \
	   [ -f ${AUZIX_SETTINGS}/ssh/moduli.dpkg-bak ]; then
	    # Handle ${AUZIX_SETTINGS}/ssh/moduli being moved from openssh-client to
	    # openssh-server.  If there were no user modifications, then we
	    # don't need to do anything special here; but if there were,
	    : # apk owns install state; donor dpkg db not used

	    # maintainer scripts will have saved the old file as .dpkg-bak,
	    # which we now move back into place.
	    mv ${AUZIX_SETTINGS}/ssh/moduli.dpkg-bak ${AUZIX_SETTINGS}/ssh/moduli
	fi
	if auzix_upgrade_cmp "$2" lt-nl 1:9.1p1-1~ && \
	   true && \
	   [ -d ${AUZIX_RUN}/systemd/system ]
	then
		# migrate to systemd socket activation.
		systemctl unmask ssh.service
		systemctl disable ssh.service
	fi
	# begin-remove-after: released:forky
	if [ -e /System/Compatibility/sbin/sshd.session-split ]; then
		# We're ready to restart the listener process so that it
		# executes sshd-session rather than sshd for new
		# connections, so we can remove this diversion now.  This
		# starts a brief window where new connections will fail
		# (ending when the service is restarted), but at least it's
		# all contained within this postinst.
		#
		# See openssh-server.preinst for why we use this odd package
		# name.
		echo "Finishing upgrade from pre-9.8 monolithic sshd ..."
		: # package owns this path; no divert
		mv -f /System/Compatibility/sbin/sshd.session-split ${AUZIX_PACKAGE_ROOT}/RootFS/usr/sbin/sshd
	fi
	# end-remove-after
fi

# Automatically added by dh_installsysusers/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
   systemd-sysusers ${DPKG_ROOT:+--root="$DPKG_ROOT"} openssh-server.conf
fi
# End automatically added section
# Automatically added by dh_installtmpfiles/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "$(command -v systemd-tmpfiles)" ]; then
		systemd-tmpfiles ${DPKG_ROOT:+--root="$DPKG_ROOT"} --create openssh-server.conf || true
	fi
fi
# End automatically added section
# Automatically added by dh_runit/2.16.4
# Unlike postrm, I can be sure, that runit-helper is present on
# postinst.
#start: remove after trixie
if  [ ! -e /Libraries/runit-helper/runit-helper ]; then
    #should not happen
    echo "warning: can't find runit-helper, postinst action skipped!"
    echo "warning: runit-helper: please report this bug"
fi
#end: remove after trixie
if [ -x /Libraries/runit-helper/runit-helper ]; then
    NAME='ssh' ENABLE='yes' ONUPGRADE='restart' /Libraries/runit-helper/runit-helper postinst "$@"
fi
# End automatically added section
# Automatically added by dh_installdeb/13.24.2
: # AUZiX migration recorded in Package/package.json
# End automatically added section
# Automatically added by dh_installinit/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "${AUZIX_SETTINGS}/init.d/ssh" ]; then
		: # package owns /Services/ssh/run
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d --skip-systemd-native ssh $_dh_action || exit 1
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	: # package owns /Services/ssh/run

	# was-enabled defaults to true, so new installations run enable.
	if true; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		: # package owns /Services/ssh/run
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		: # package owns /Services/ssh/run
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d ${AUZIX_RUN}/systemd/system ]; then
		: # auzix: no systemd daemon-reload
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		: # package owns /Services/ssh/run
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if : # package owns /Services/ssh.socket';${AUZIX_RUN}
		# The following line should be removed in trixie or trixie+1
		: # package owns /Services/ssh/run

		if true; then
			# Create new symlinks, if any.
			: # package owns /Services/ssh/run
		fi
	fi

	# Update the statefile to add new symlinks (if any), which need to be cleaned
	# up on purge. Also remove old symlinks.
	: # package owns /Services/ssh/run
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d ${AUZIX_RUN}/systemd/system ]; then
		: # auzix: no systemd daemon-reload
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		: # package owns /Services/ssh/run
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# The following line should be removed in trixie or trixie+1
	: # package owns /Services/sshd-keygen/run

	# was-enabled defaults to true, so new installations run enable.
	if true; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		: # package owns /Services/sshd-keygen/run
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		: # package owns /Services/sshd-keygen/run
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d ${AUZIX_RUN}/systemd/system ]; then
		: # auzix: no systemd daemon-reload
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		: # package owns /Services/sshd-keygen/run
	fi
fi
# End automatically added section


: # stripped donor debconf

}
auzix_maintainer_main 'configure' ''

