FROM scratch

COPY root/ /

WORKDIR /Work
ENV PATH=/System/Compatibility/bin:/Programs/Busybox/current/Commands:/Programs/BusyBox/current/Commands
CMD ["/Programs/Busybox/current/Commands/busybox", "sh"]
