services:
  builder:
    build:
      context: .
      dockerfile: docker/builder/Dockerfile
    image: auzix/builder:local
    working_dir: /workspace
    environment:
      AUZIX_ROOT_SOURCE: /workspace/out/auzix-strict/AuzixRoot
      AUZIX_ISO_NAME: auzix-strict-shell.iso
    volumes:
      - .:/workspace
      - ./out:/workspace/out
      - ./artifacts:/workspace/artifacts
      - auzix-cache:/root/.cache
    command: ["./scripts/build-auzix-strict-all.sh"]

  shell:
    image: auzix/builder:local
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ./out:/workspace/out
      - ./artifacts:/workspace/artifacts
      - auzix-cache:/root/.cache
    command: ["bash"]
    profiles: ["shell"]

  installer-builder:
    build:
      context: .
      dockerfile: docker/installer-builder/Dockerfile
    image: auzix/installer-builder:local
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ./out:/workspace/out
    command:
      - bash
      - -lc
      - ./scripts/build-auzix-package-tools-package.sh && ./scripts/build-auzix-installer-package.sh && ./scripts/test-auzix-installer.sh
    profiles: ["installer"]

volumes:
  auzix-cache:
