server {
    listen 80 default_server;
    server_name _;

    location /netboot/ {
        alias /srv/netboot/;
        autoindex on;
    }

    location /pxe/ {
        alias /srv/pxe/;
        autoindex on;
    }

    location /auzix/ {
        alias /srv/http/auzix/;
        autoindex off;
    }
}
