#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PACKAGE="${1:?usage: rake-auzix-source-port.sh <debian-source-package> [all|path-hunt]}"
MODE="${2:-all}"
PORT_ROOT="${ROOT_DIR}/out/auzix-source-ports/${PACKAGE}"
SOURCE_PARENT="${PORT_ROOT}/debian-source"
AUZIX_SOURCE="${PORT_ROOT}/auzix-source"
CONTRACT_DIR="${PORT_ROOT}/contract"
REPORT_DIR="${PORT_ROOT}/reports"

log() {
  printf '[auzix-source-port] %s\n' "$*" >&2
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'missing required command: %s\n' "$1" >&2
    exit 1
  }
}

fetch_source() {
  mkdir -p "${SOURCE_PARENT}"
  if find "${SOURCE_PARENT}" -mindepth 1 -maxdepth 1 -type d -name "${PACKAGE}-*" -print -quit | grep -q .; then
    return
  fi
  (
    cd "${SOURCE_PARENT}"
    apt-get source "${PACKAGE}"
  )
}

source_dir() {
  find "${SOURCE_PARENT}" -mindepth 1 -maxdepth 1 -type d -name "${PACKAGE}-*" -print | sort | tail -n 1
}

capture_recipe() {
  local src="$1"
  mkdir -p "${CONTRACT_DIR}" "${REPORT_DIR}"
  "${ROOT_DIR}/scripts/inspect-debian-source-contract.sh" "${PACKAGE}" "${PORT_ROOT}/guidebook" >/tmp/auzix-source-port-guidebook.log 2>&1 || {
    cat /tmp/auzix-source-port-guidebook.log >&2
    return 1
  }
  cp -f "${PORT_ROOT}/guidebook/report/guidebook.md" "${CONTRACT_DIR}/debian-guidebook.md"
  cp -f "${src}/debian/control" "${CONTRACT_DIR}/debian-control"
  cp -f "${src}/debian/rules" "${CONTRACT_DIR}/debian-rules"
  find "${src}/debian" -maxdepth 1 -type f \
    \( -name '*.install' -o -name '*.links' -o -name '*.dirs' -o -name '*.postinst' -o -name '*.preinst' -o -name '*.postrm' -o -name '*.prerm' -o -name '*.triggers' \) \
    -exec cp -f {} "${CONTRACT_DIR}/" \;
}

materialize_source() {
  local src="$1"
  rm -rf "${AUZIX_SOURCE}"
  mkdir -p "${AUZIX_SOURCE}"
  rsync -a --exclude='.pc' "${src}/" "${AUZIX_SOURCE}/"
  mkdir -p "${AUZIX_SOURCE}/auzix"
  cat >"${AUZIX_SOURCE}/auzix/README.md" <<EOF
# AUZiX source port: ${PACKAGE}

This tree is materialized from Debian source, then patched/configured for AUZiX
path policy. Debian packaging remains the source recipe; AUZiX adds explicit
path transforms, package split contracts, wrappers, validation, and FPM/staged
package output.

Generated by:

\`\`\`
rake source:port[${PACKAGE}]
\`\`\`
EOF
  cat >"${AUZIX_SOURCE}/auzix/path-policy.sed" <<'EOF'
# AUZiX source-port path policy scratchpad.
# Keep substitutions narrow and evidence-backed. Prefer build/configure flags
# before source edits. Do not add blanket /usr rewrites here.
EOF
}

write_contract_json() {
  local src="$1"
  python3 - "${PACKAGE}" "${src}" "${PORT_ROOT}" >"${CONTRACT_DIR}/source-port.contract.json" <<'PY'
import json
import pathlib
import re
import sys

package, src_arg, port_arg = sys.argv[1:4]
src = pathlib.Path(src_arg)
port = pathlib.Path(port_arg)
control = (src / "debian/control").read_text(encoding="utf-8")

def paragraphs(text):
    out, cur = [], []
    for line in text.splitlines():
        if not line.strip():
            if cur:
                out.append("\n".join(cur)); cur = []
        else:
            cur.append(line)
    if cur:
        out.append("\n".join(cur))
    return out

def fields(para):
    result, key = {}, None
    for line in para.splitlines():
        if line[:1].isspace() and key:
            result[key] += " " + line.strip()
        elif ":" in line:
            key, value = line.split(":", 1)
            result[key] = value.strip()
    return result

def split_deps(value):
    if not value:
        return []
    deps = []
    for raw in value.split(","):
        raw = re.sub(r"\[[^\]]*\]|<[^>]*>|\([^)]*\)", "", raw).strip()
        if not raw:
            continue
        alts = [part.strip() for part in raw.split("|") if part.strip()]
        deps.append(alts if len(alts) > 1 else alts[0])
    return deps

paras = [fields(p) for p in paragraphs(control)]
source = paras[0]
binaries = [p for p in paras[1:] if "Package" in p]
install_manifests = {}
for path in sorted((src / "debian").glob("*.install")):
    install_manifests[path.name] = [
        line.strip() for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]

contract = {
    "format": "auzix-source-port-contract-v1",
    "id": package,
    "source": {
        "type": "debian-source",
        "package": source.get("Source", package),
        "local_source": str(src),
    },
    "auzix_source": str(port / "auzix-source"),
    "debian": {
        "build_depends": split_deps(source.get("Build-Depends", "")),
        "rules_requires_root": source.get("Rules-Requires-Root"),
        "binary_packages": [],
        "install_manifests": install_manifests,
    },
    "build_queue": {
        "policy": "Build dependencies are AUZiX package candidates too; source build setup and target runtime closure come from the same Debian recipe.",
        "packages": [],
    },
    "pipeline": {
        "steps": [
            "fetch-debian-source",
            "capture-debian-recipe",
            "derive-build-dependency-queue",
            "materialize-auzix-source-tree",
            "hardwired-path-hunt",
            "apply-narrow-path-policy",
            "build-using-debian-rules-or-declared-build-system",
            "stage-package-splits",
            "fpm-package-staged-tree",
            "generate-auzix-receipts-wrappers",
            "validate-and-promote"
        ],
        "path_policy": "Prefer configure/build flags. Use sed patches only when source/packaging hardwires donor paths.",
    },
    "auzix_stage_policy": {
        "donor_binary_build": "proof/calibration only; AUZiX package output is built from source recipe plus AUZiX path contract",
        "dependency_policy": "Build source dependencies and runtime dependencies as AUZiX packages before the target package.",
        "fpm_policy": "Use FPM dir source=destination mappings for staged package output after AUZiX configure/path transforms.",
        "path_knobs": {
            "prefix": "/Programs/<Package>/current",
            "sysconfdir": "/System/Settings",
            "localstatedir": "/System/State",
            "libexecdir": "/Programs/<Package>/current/Helpers",
            "datadir": "/Programs/<Package>/current/Shared"
        }
    },
}

for binary in binaries:
    contract["debian"]["binary_packages"].append({
        "package": binary.get("Package"),
        "architecture": binary.get("Architecture"),
        "depends": split_deps(binary.get("Depends", "")),
        "recommends": split_deps(binary.get("Recommends", "")),
        "suggests": split_deps(binary.get("Suggests", "")),
        "description": binary.get("Description", ""),
    })

queued = {}
def add_queue(dep, reason, binary_package=None):
    items = dep if isinstance(dep, list) else [dep]
    for index, item in enumerate(items):
        if not item or item.startswith("${"):
            continue
        key = item
        entry = queued.setdefault(key, {
            "debian_package": item,
            "reasons": [],
            "preferred_alternative": index == 0,
        })
        why = {"reason": reason}
        if binary_package:
            why["binary_package"] = binary_package
        if why not in entry["reasons"]:
            entry["reasons"].append(why)

for dep in contract["debian"]["build_depends"]:
    add_queue(dep, "source-build-dependency")
for binary in contract["debian"]["binary_packages"]:
    for dep in binary["depends"]:
        add_queue(dep, "runtime-dependency", binary["package"])
    for dep in binary["recommends"]:
        add_queue(dep, "runtime-recommendation", binary["package"])

contract["build_queue"]["packages"] = [queued[name] for name in sorted(queued)]

print(json.dumps(contract, indent=2, sort_keys=True))
PY
}

path_hunt() {
  mkdir -p "${REPORT_DIR}"
  {
    printf '# AUZiX hardwired path hunt: %s\n\n' "${PACKAGE}"
    printf '## Text hits\n\n'
    grep -RInE --exclude-dir=.git --exclude-dir=.pc \
      '/usr|/etc|/var|/bin|/sbin|/lib|/run|/tmp' "${AUZIX_SOURCE}" 2>/dev/null || true
    printf '\n## ELF/string hits\n\n'
    while IFS= read -r file_path; do
      if file "${file_path}" | grep -q 'ELF'; then
        strings "${file_path}" | grep -E '/usr|/etc|/var|/bin|/sbin|/lib|/run|/tmp' |
          sed "s#^#${file_path}: #"
      fi
    done < <(find "${AUZIX_SOURCE}" -type f -perm /111 2>/dev/null)
  } >"${REPORT_DIR}/hardwired-paths.md"
  log "path hunt report: ${REPORT_DIR}/hardwired-paths.md"
}

build_plan() {
  local src="$1"
  [[ -f "${CONTRACT_DIR}/source-port.contract.json" ]] || {
    capture_recipe "${src}"
    materialize_source "${src}"
    write_contract_json "${src}"
    path_hunt
  }
  python3 - "${CONTRACT_DIR}/source-port.contract.json" <<'PY'
import json, sys
contract = json.load(open(sys.argv[1], encoding="utf-8"))
print(f"# AUZiX source build plan: {contract['id']}")
print()
print("## Build order policy")
print(contract["build_queue"]["policy"])
print()
print("## Debian source recipe")
print(f"- source package: {contract['source']['package']}")
print(f"- rules-requires-root: {contract['debian'].get('rules_requires_root') or 'unspecified'}")
print("- build system: Debian rules/debhelper recipe; use donor package build only as proof, not final output")
print()
print("## Build dependency queue")
for item in contract["build_queue"]["packages"]:
    reasons = ", ".join(
        r["reason"] + (f":{r['binary_package']}" if "binary_package" in r else "")
        for r in item["reasons"]
    )
    alt = "" if item.get("preferred_alternative", True) else " (alternative)"
    print(f"- {item['debian_package']}{alt} [{reasons}]")
print()
print("## Binary split surfaces")
for binary in contract["debian"]["binary_packages"]:
    print(f"- {binary['package']} ({binary.get('architecture') or 'arch?'})")
print()
print("## Install manifests")
for name, lines in contract["debian"]["install_manifests"].items():
    print(f"- {name}: {', '.join(lines)}")
print()
print("## AUZiX stage policy")
stage = contract.get("auzix_stage_policy", {})
for key in ("donor_binary_build", "dependency_policy", "fpm_policy"):
    if stage.get(key):
        print(f"- {stage[key]}")
knobs = stage.get("path_knobs") or {}
for key, value in knobs.items():
    print(f"- {key}: {value}")
PY
}

install_build_deps() {
  local src="$1"
  local source_name
  source_name="$(awk -F: '/^Source:/ { gsub(/^[ \t]+|[ \t]+$/, "", $2); print $2; exit }' "${src}/debian/control")"
  [[ -n "${source_name}" ]] || source_name="${PACKAGE}"
  log "installing Debian build dependencies for ${source_name}"
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get build-dep -y "${source_name}"
}

debian_build() {
  local src="$1"
  mkdir -p "${REPORT_DIR}"
  log "running Debian binary build recipe for ${PACKAGE}"
  (
    cd "${src}"
    DEB_BUILD_OPTIONS="${DEB_BUILD_OPTIONS:-nocheck}" \
      dpkg-buildpackage -us -uc -b
  ) 2>&1 | tee "${REPORT_DIR}/debian-build.log"
  {
    printf '# Debian build artifacts: %s\n\n' "${PACKAGE}"
    find "${SOURCE_PARENT}" -maxdepth 1 -type f \
      \( -name '*.deb' -o -name '*.changes' -o -name '*.buildinfo' \) \
      -printf '%f\t%s bytes\n' | sort
  } >"${REPORT_DIR}/debian-build-artifacts.tsv"
  log "Debian build log: ${REPORT_DIR}/debian-build.log"
  log "Debian build artifacts: ${REPORT_DIR}/debian-build-artifacts.tsv"
}

require_cmd apt-get
require_cmd rsync
require_cmd python3
require_cmd grep
require_cmd strings
require_cmd file

fetch_source
SRC_DIR="$(source_dir)"
[[ -n "${SRC_DIR}" ]] || {
  log "source directory not found for ${PACKAGE}"
  exit 1
}

if [[ "${MODE}" == "path-hunt" ]]; then
  [[ -d "${AUZIX_SOURCE}" ]] || materialize_source "${SRC_DIR}"
  path_hunt
  exit 0
fi

if [[ "${MODE}" == "build-deps" ]]; then
  install_build_deps "${SRC_DIR}"
  exit 0
fi

if [[ "${MODE}" == "build-plan" ]]; then
  build_plan "${SRC_DIR}"
  exit 0
fi

if [[ "${MODE}" == "debian-build" ]]; then
  debian_build "${SRC_DIR}"
  exit 0
fi

capture_recipe "${SRC_DIR}"
materialize_source "${SRC_DIR}"
write_contract_json "${SRC_DIR}"
path_hunt
log "AUZiX source port staged: ${PORT_ROOT}"
